# Generated by Django 4.1.3 on 2022-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('year_of_experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='expertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
                ('skill_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professional_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('education_level', models.CharField(max_length=100)),
                ('ed_year', models.CharField(max_length=100)),
                ('ed_place', models.CharField(max_length=100)),
                ('educ_experience_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
