# Generated by Django 4.1.3 on 2022-11-19 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='nameof_pr',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
