# Generated by Django 4.1.3 on 2022-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=150)),
                ('insta', models.CharField(max_length=150)),
                ('telegram', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
            ],
        ),
    ]
