# Generated by Django 4.1.3 on 2022-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='about_pics/'),
        ),
    ]
